--populare furnizori bucuresti
ALTER TABLE furnizori
ADD CONSTRAINT UQ_denumire_furnizor UNIQUE (denumire_furnizor);
select * from Furnizori

INSERT INTO furnizori (denumire_furnizor)
VALUES
  ('SC APA TALEA SRL'),
  ('SC ALIMAR OEM SRL'),
  ('SC VIOSIL INSTALCONSTRUCT SRL'),
  ('SC BRAMCO CONRECON SRL'),
  ('SC ELITEX SRL'),
  ('SC AB INSTAL SRL'),
  ('SC SCUDIVER TOOLS SRL'),
  ('SC RIAN CONSULT SRL'),
  ('SC EMON SRL'),
  ('SC CARANDA BATERII SRL'),
  ('SC GRAL MEDICAL SRL'),
  ('SPITALUL CLINIC CF 2 BUCURESTI'),
  ('SC ROMOLD SRL'),
  ('SC ALSIMCRIS UTIL SRL'),
  ('SC TISECO SRL'),
  ('SC EURO VIAL LIGHTING SRL'),
  ('SC TRANS-BLAN MOROSAN SRL'),
  ('SC CONCEPT CREATIV CONTSRUCT SRL'),
  ('SC PSICOM GLOBAL SRL'),
  ('SC PIN PLUS PIN SRL'),
  ('SC ARTEGO SA'),
  ('SC SERVICII SALUBRITATE BUCURESTI SA'),
  ('SC GRAFORESS SRL'),
  ('SC OZON SERV SRL'),
  ('SC POLYGON TRADING SRL'),
  ('SC PRODUCTON SRL'),
  ('SC SAFETY SECURITY SRL'),
  ('SC ACTIV PROIECT SRL'),
  ('SC MASTERY ELECTRONICS SRL'),
  ('SC DOCSYS ARHIVARE SRL'),
  ('SC NOVATECH SRL'),
  ('SC MULTILAB SRL'),
  ('SC CONCEPT CREATIV CONSTRUCT SRL'),
  ('SC DOLEX COM SRL'),
  ('SC ARCHIPRO CONSTRUCT SRL'),
  ('SC CORSAL ONLINE SRL'),
  ('SC BIROTIC SRL'),
  ('SC ECOLAB CONSULT SRL'),
  ('SC RAMA CLAU SRL'),
  ('SC GEFIL SA'),
  ('SC DUOTRAC SRL'),
  ('Romprest Servicii Integrate srl'),
  ('GES FORCE SRL'),
  ('SC ALL STRADE CONSTRUCT & TEHNOLOGY SRL'),
  ('SC IPROCHIM SA'),
  ('SC MECHANIC &HYDRO-PNEUMATIC SYSTEM SRL'),
  ('SC ECOTRANS ROMANIA SRL'),
  ('SC VIOSIL INSTAL CONSTRUCT SRL'),
  ('SC MEDIMPACT SA'),
  ('SC Reactiv Prod Com SRL'),
  ('SC  Adam El - Tenso SRL'),
  ('SC LSG Interserv SRL'),
  ('SC Union CO SRL'),
  ('SC Profesional Security Divizion SRL'),
  ('SC Gamiatricos Com SRL'),
  ('SE Biservconstruct SRL'),
  ('SC Romprest Servicii Integrate SRL'),
  ('SC Kaesser Kompressoren SRL'),
  ('SC One Star Seurity SRL'),
  ('SC Aspad Com SRL'),
  ('SC Electroputere AIT SRL'),
  ('SC Census Group SRL'),
  ('SC Selena System SRL'),
  ('SC Dune Consulting Service SRL'),
  ('SC Mirror Group Print SRL'),
  ('SC DDA Birotica SRL'),
  ('SC IPROEX ENERGY MANAGEMENT SRL'),
  ('SC Royal Eurotrans SRL'),
  ('SC RER ECOLOGIC SERVICE BUCURESTI REBU SA'),
  ('SC ULTRA FRESH IMPEX SA'),
  ('SC MESSYSTECH SRL'),
  ('SC SPARTAN PAZA SI PROTECTIE SRL'),
  ('SC ALDO SECURITY SRL'),
  ('SC KRASZTEL&ASOCIATII SRL'),
  ('SC EOS CORPORATION SRL'),
  ('SC MOBILIS SRL'),
  ('SC FIRE&RESCUE SERVICES SRL'),
  ('SC DNS BIROTICA SRL'),
  ('SC MURAL SERV SEL'),
  ('SC MOD-ELLE COMPANY SRL'),
  ('SC TRANSBLAN MOROSAN SRL'),
  ('SC PROFICONS PROJECT SRL'),
  ('SC GES FORCE SRL'),
  ('SC NIADA AUDITAX EXPERT SRL'),
  ('SC DUNIAG INSTAL SRL'),
  ('SC DRAGON STAR'),
  ('SC TOTAL BUSINESS LAND SRL si SC ALS LIFE SCIENCE ROMANIA SRL (asociat)'),
  ('SC RELOC SA'),
  ('SC BISERVCONSTRUCT SRL'),
  ('Spalatoria Edelweiss SRL'),
  ('SC ROMCARBON SRL'),
  ('SC GRAL MEDICAL'),
  ('SC ARCA MONDO CHIM SRL'),
  ('SC RIANCONSULT SRL'),
  ('SC EURO CONSTRUCT SRL'),
  ('SC OLIMP CONSTRUCT SRL'),
  ('SC SIGILMAR PROD SRL'),
  ('SC FRIGOKOM TRADING SRL'),
  ('SC RAMA CLAU'),
  ('SC DRIFT SERV  SRL'),
  ('SC Tehnica Noua Libera SRL'),
  ('SC Super Ball SRL'),
  ('Banca Comerciala Romana'),
  ('SC MIRROR GROUP SRL'),
  ('SC ULTRA FRESH IMPEX SRL'),
  ('SC UTI GRUP SA'),
  ('SC KAESER KOMPRESSOREN SRL'),
  ('SC COMPLET SERVICE SRL'),
  ('SC SIEMENS SRL'),
  ('SC Ecogreen Construct SRL'),
  ('S.C. Cipimartex Distribution SRL'),
  ('SC La Fantana SRL'),
  ('SC PROFITECH TRADE & SERVICE SRL'),
  ('SC CRISTAN PRODEXIM SRL'),
  ('SC SILGIMAR PROD SRL'),
  ('SC SUPERKLIMA INSTALATII SRL'),
  ('SC DRAGON OIL STAR SRL'),
  ('SC RER ECOLOGIC SERV SRL'),
  ('SC TERMOENERGETICA INSTAL SRL'),
  ('SC SOFTRONIC SRL'),
  ('SC TANOPEX SRL'),
  ('SC DINALUCRI SRL'),
  ('SC NGM COMPANY SRL'),
  ('SC EDG EDIL Pitesti SRL'),
  ('SC Progresu Profi Tools SRL'),
  ('SC Fire & Rescue Service SRL'),
  ('SC Evident Grup SRL'),
  ('SC BISERVCONSTRUCTFAB SRL'),
  ('SC IRRECSON EVALUARI SRL'),
  ('SC MIDA SOFT BUSINESS SRL'),
  ('SC SETCAR SA'),
  ('SC DLA PIESE SI ACCESORII SRL'),
  ('SC EUROCONSTRUCT SA'),
  ('SC INTERBABIS SRL'),
  ('SC INEDIT CLEAN SRL'),
  ('SC DRIFT SRL'),
  ('BANCA COMNERCIALA ROMANA SA'),
  ('SC RAR ADVERTISING MEDIA SRL'),
  ('SC BIOSOL SRL'),
  ('SC GECOR SRL'),
  ('SC Electroaparataj Tractiune SRL'),
  ('SC PFA MOCANU SRL'),
  ('SC MODAVIL SRL'),
  ('SC Heating & Cooling Engeneering SRL'),
  ('SC EVW Holding SRL'),
  ('SC VECTRA EXIM SRL'),
  ('SC DEVAX MOTORS'),
  ('SC TURKROM SRL'),
  ('SC CONTRANS IMPEX SRL'),
  ('SC MURAL SERV SRL'),
  ('SC LINDE GAZ Romania'),
  ('SC DELTA PRESS SRL'),
  ('SC CRISTAN IMPEX SRL'),
  ('SC RINO GUARD SRL'),
  ('COMPANIA ROMPREST SERVICE SA'),
  ('SC ALMATAR TRANS SRL'),
  ('SC VFM INTERCOM SRL'),
  ('SC BERMI GENERAL SRL'),
  ('SC PROFESIONAL SECURITY DIVISION SRL'),
  ('SC ProConfort Distribution Carpet SRL'),
  ('SC AC CONFORT& SAFETY SYSTEMS SRL'),
  ('SC OZON SERV PROD SRL'),
  ('SC EURIAL SRL'),
  ('SC TOTAL BUSINESS TECHNOLOGIES SRL'),
  ('S & T ROMANIA SRL'),
  ('SC ARTEGO SRL'),
  ('SC GLOBAL SISTEM SRL'),
  ('SC EVIDENT GROUP SRL'),
  ('SC ECONATURALIA SRL'),
  ('SC Profi Cons Project SRL'),
  ('SC ARMAX INDBEST LINE SRL'),
  ('SC ECOQUALITY Services SRL'),
  ('SC INTEGRA GUARD SRL'),
  ('SC EUROTRANS INDUSTRY SRL'),
  ('SC MONORADAS SRL'),
  ('Compania Nationala pentru Controlul Cazanelor, Instalatiilor de ridicat su Recipientelor sub Presiune CNCIR SA'),
  ('SC Carland SRL'),
  ('SC F & R Workdwide SRL'),
  ('SC SGPI SECURITY FORCE SRL'),
  ('SC PROFLEX SRL'),
  ('SC K-ELICOM TRADING SRL'),
  ('SC AUSTING COM SRL'),
  ('SC SELECT PRINT SRL'),
  ('SC OSTROVIL SA'),
  ('SC MOPEKA SRL'),
  ('SC REM ROX SRL'),
  ('SC Sara Transport SRL'),
  ('SC SECURITY SUPPORT COURSES SRL'),
  ('SC MATRAGAL SRL'),
  ('SC NIADA AUDITAX SRL'),
  ('SC IZOSERV CONSTRUCT SRL'),
  ('SC COMPACT CONART SRL'),
  ('SC ALLCHIM DDD CO SA'),
  ('SC FIRST VERSE DANTE SRL'),
  ('SC FRANGOMY SOLUTION SRL'),
  ('SC HESTIA CONSTRUCTII MONTAJ SRL'),
  ('SC UTI Building SRL'),
  ('SC  RIFANIA DRUMCONSTRUCT SRL'),
  ('SC MURAL SERV SRL cu asociat  SC TUDOR ARHCONS SRL'),
  ('SC IRECSON EVALUARI SRL'),
  ('SC COLIMO SRL'),
  ('SC K-ELICOM SRL'),
  ('SC FIRST VERSTE DANTE SRL'),
  ('SC PLUSTER PROTECT SRL'),
  ('SC GEOAGRI CADASTRU SRL'),
  ('SC EUROTOTAL COMPANY SRL'),
  ('BANCA COMERCIALA ROMANA SA'),
  ('SC OMNITECH ELECTRIC SRL'),
  ('SC 2C INSTAL GAZ BUSINESS SRL'),
  ('SC EUROCONTRUCT SA'),
  ('SC SEDA INVEST SRL'),
  ('SC SUPERBALL SRL'),
  ('SC TRANSLIMA SRL'),
  ('SC Reparatii Centrale SRL'),
  ('SC Silgimar SRL'),
  ('SC DIRECTOR SPECIAL TROOPS SRL'),
  ('SC K-ELICOM'),
  ('SC CORPORATION SITUATII DE URGENTA SRL'),
  ('SC ATELIERELE CFR GRIVITA'),
  ('SC Mural Serv SRl (sub asociat SC Tudor Arhcons SRL)'),
  ('SC TOKO SRL'),
  ('SC Drift  Serv SRL'),
  ('SC Energobit SRL'),
  ('Confermet Industrial SA'),
  ('SC Romanian Security Sistems (cu subcontractant SC SGPI Security SRL)'),
  ('SC PFA Nitoi Mihai'),
  ('SC PROTECT COLECTOR SRL'),
  ('SC Tesla Power Systems SRL'),
  ('SC SAT CCH Development SRL'),
  ('SC Cristian Prodexim SRL'),
  ('SC KEMOXEL SRL'),
  ('Cabinet Individual de Expertize Tehnice Judiciare si Extrajudiciare Dr.ing. Mihai'),
  ('IRECSON EVALUARI'),
  ('SC AMIA INVEST SRL'),
  ('SC REVA SA'),
  ('SC C&C PREVENT SRL'),
  ('SC ARC BRASOV SRL'),
  ('SC BUSINESS DEVELOPMENT TEAM'),
  ('SC ELECMOND ELECTRIC SRL'),
  ('CNCIR SA'),
  ('SC Direct Retail Distribution SRL'),
  ('SC I&L TECHNOCONSULTING SRL'),
  ('SC PROFICOM TEXTIL SRL'),
  ('PFA MOCANU IULIAN'),
  ('SC TRIBAG SRL'),
  ('SC ROMASI SERVICE SRL'),
  ('SC VIKMAR SERV SRL'),
  ('SC DIRECTOR TROOPS SRL'),
  ('SC AQVA TERMO SANIT SRL'),
  ('SC ROMPETROL DOWNSTREAM SRL'),
  ('SC CHROME COMPUTERS SRL'),
  ('SC EUROSTING AAW INDUSTRY SRL'),
  ('SC EUROTOTAL COMP SRL'),
  ('SCARTEGO SRL'),
  ('SC STANDARD MOB DESIGN SRL'),
  ('SC TRYAMM TRADING CONSULTING SRL'),
  ('AC COMFORT SECURITY SRL'),
  ('SC PROFESSIONAL SECURITY DIVISION'),
  ('SC BISERVCONSTRUCTFAB  SRL'),
  ('SC FRIGOKOM IMPEX SRL'),
  ('SC DRIFT SERV SRL'),
  ('SC METALSIM COMPANY SRL'),
  ('SC BRIGHT ENGINEERING SRL'),
  ('VFM INTERCOM SRL'),
  ('SC RONERA RUBBERA SA'),
  ('SC MEDICAL CENTER GRAL'),
  ('SC PRODIVEX SRL'),
  ('SC INEDIT CLEAN TOTAL SRL'),
  ('SIGILROM COMPANY SRL'),
  ('SC FEROM SRL'),
  ('SC VIC INSERO SRL'),
  ('SC ENGINEERING BUSINESS SOLUTIONS SRL'),
  ('SC APPRAISAL & VALUATION SA');

 --Craiova
 INSERT INTO furnizori (denumire_furnizor)
VALUES
  ('SC OSCAR DOWNSTREAM SRL'),
  ('SC RO COMPUTER SRL'),
  ('SC NED COM SRL'),
  ('SC CONPHYS SRL'),
  ('SC LOCOMOTIVA SRL'),
  ('SC MILANO PAPETARIE SRL'),
  ('SC G4S Cash Solutions SRL'),
  ('SC SUCCES NIC COM SRL'),
  ('SC TEPACOS SRL'),
  ('SC GDO MOV IMPEX SRL'),
  ('SC QUASAR SA Deva'),
  ('SC TERRA SILVA SRL'),
  ('SC GRUP EST SECURITY SRL'),
  ('SC BIOTA COM SRL'),
  ('SC PRIMASERV SRL'),
  ('SC MANOPRINTING SRL'),
  ('SC DANEROM SRL'),
  ('SC TEPACOS COMPANY SRL'),
  ('SC MAGNIS SRL'),
  ('SC GAS CASH SOLUTION SRL'),
  ('SC EUROPAN PROD SRL'),
  ('SC PLUS AUTO SRL'),
  ('SC ELECTRIC RAIL PROJECT SRL'),
  ('SC UNION PROTECTION SRL'),
  ('Spitalul Clinic CF Craiova'),
  ('SC RARVALSERV SRL'),
  ('SC DDA BIROTICA OFFICE SRL'),
  ('SC SYSCOM-18 SRL'),
  ('SC GES FORCES SRL'),
  ('SC CON METAL CF SRL'),
  ('SC SHAROLT GROUP SRL'),
  ('SC VEST CONSTRUCT SRL'),
  ('SC MINEXFOR SA'),
  ('RAM SECURITY SERVICE SRL'),
  ('SC ALSTINGTIM SERV SRL'),
  ('Asociere SC INDUSTRIAL CONSTRUCT GEDI SRL - SC DAMIENA SRL'),
  ('EUROPAN PROD.SA'),
  ('SC MEDA CONSULT SRL'),
  ('BCR S.A'),
  ('SA ARMOS SERVICE SRL'),
  ('SC MEDIMPACT S.A.'),
  ('MINEXFOR S.A.'),
  ('SC RINA SIMTEX ORGANISMUL DE CERTIFICARE SRL'),
  ('SC ELECTRIC VALCOR SRL'),
  ('SC STENMARSERV SRL'),
  ('PROTECT NPG SRL cu subcontractantul SC ROMANIAN SECURITY SYSTEMS SRL.'),
  ('SC SCADT SA'),
  ('Esd Expert Oprea S.R.L.'),
  ('BCR cu tert sustinator CIT ONE SRL'),
  ('SC FORMENERG SA'),
  ('SC LENOX SRL'),
  ('SC ANTARES ROMANIA SRL'),
  ('SC EXPERTISSA HQ SRL'),
  ('S.C. SITCO SERVICE SRL'),
  ('SC JOBMED SRL cu CIP PERSU ADRIANA NATALIA'),
  ('CON METAL CF SRL'),
  ('CNCIR S.A'),
  ('FORTUNA SECURITY'),
  ('RARVALSERV SRL'),
  ('ARTEGO SA'),
  ('MANOPRINTING SYSTEM SRL'),
  ('CN Imprimeria Nationala SA'),
  ('SPIACT CRAIOVA SA'),
  ('BCR SA cu tert sustinator SC CIT One SRL'),
  ('C&C PREVENT SRL'),
  ('MIRROR GROUP PRINT SRL-D'),
  ('SHAROLT GROUP SRL'),
  ('C&C PRVENT SRL'),
  ('OMNIASIG VIENNA INSURANCE GROUP SA'),
  ('SC BRESCIA PROD COM SRL'),
  ('SC RO-COMPUTER SRL'),
  ('CNCIR S.A. - Compania Nationala pentru Controlul Cazanelor, Instalatiilor de Ridicat si Recipientelor sub presiune'),
  ('GLOBAL PLAST HORECA SRL'),
  ('SC AVENA MEDICA SRL'),
  ('SC HANEX SRL'),
  ('SC METRANS SRL'),
  ('CONTRANS IMPEX'),
  ('SITCO SERVICE SRL'),
  ('SC LUAN VISION SRL'),
  ('SC BEST ACHIZITII SRL'),
  ('SC LORGIS SRL'),
  ('NIADA AUDITAX SRL'),
  ('CMV QUALITY INSTAL SRL'),
  ('S.C. NERAMO DISTRIBUTION S.R.L.'),
  ('TOP EDGE ENGINEERING SRL'),
  ('REM ROX SRL'),
  ('NIADA AUDITAX EXPERT SRL'),
  ('SOCIETATEA COOPERATIVA MESTESUGAREASCA DE GRADUL 1 SOLIDARITATEA IASI'),
  ('MEDA CONSULT'),
  ('FAST BROKERS'),
  ('EXPERTIZA JUDICIARA OLARU SI ASOCIATII'),
  ('METRANS SRL'),
  ('CERTINVEST SRL'),
  ('LOCOMOTIVA SRL'),
  ('MEDA CONSULT SRL'),
  ('PROUTIL SERVICE SRL'),
  ('TERRA SILVA SRL'),
  ('PROTECT NPG PAZA S.R.L.'),
  ('EVIDENT GROUP SRL'),
  ('ALISON HAYES ( ROMANIA ) SRL'),
  ('Asocierea BCR SA- CIT ONE SA'),
  ('CONTRANS IMPEX SRL'),
  ('IOANA N&M SRL'),
  ('GRANDCONSTRUCT SRL'),
  ('BLANARIU MIHAIL PFA'),
  ('CBC HALE SRL'),
  ('FLYNG IMPEX SRL'),
  ('ELTECH SRL'),
  ('S.C. STENMARSERV S.R.L.'),
  ('S.C. FAST BROKERS - BROKER DE ASIGURARE- REASIGURARE S.R.L.'),
  ('DNS BIROTICA SRL'),
  ('NEW RDT SRL'),
  ('CUBIC EXTERN CURIER'),
  ('MEDIASTING SRL'),
  ('FRANGOMY SOLUTIONS SRL'),
  ('MINET CONF SRL'),
  ('REM-ROX SRL'),
  ('S.C. GEODATA SERVICES S.R.L.'),
  ('S.C. AB INSTAL S.R.L.'),
  ('TIPOGRAFIA PROD COM S.R.L.'),
  ('GECOR SRL'),
  ('SGPI SECURITY FORCE SRL'),
  ('LENOX PROD SRL'),
  ('RTC PROFFICE EXPERIENCE SRL'),
  ('ION SERVICE CENTER SRL'),
  ('SEDA INVEST SRL'),
  ('RDT OFFICE SRL'),
  ('BAD DOG OFFICE DISTRIBUTION SRL'),
  ('ARABESQUE SRL'),
  ('EVALUARE SI EXPERTIZA JUDICIARA OLARU SI ASOCIATII S.R.L.'),
  ('HARPEK SRL'),
  ('BENDKOPP FASTENERS IMPORT EXPORT S.R.L.'),
  ('EUROSTING SRL'),
  ('MIV CAD TOPOGRAFIE SRL'),
  ('NUTRIVET SRL'),
  ('DIRECT RETAIL DISTRIBUTION SRL'),
  ('LUK FOREST SISTEM S.R.L.');

--Timisoara

INSERT INTO furnizori (denumire_furnizor)
VALUES
('SC T-SOFT SRL'),
('SC Isal Tim SRL'),
('SC Tipografia Prod Com SRL'),
('SC Elsaco Energy SRL'),
('SC G4SCASCH SOLUTIONS SRL'),
('SC Termo Energetica Banatul SRL'),
('SC Aninoasa Tim SRL'),
('SC Tim Ciclop SRL'),
('SC GDF Suez SRL'),
('SC Producton SRL'),
('SC Andex Imp-Exp SRL'),
('SC Achizitii si Dezvoltare SRL'),
('SC Adam-El Tenso SRL'),
('SC Maticom SRL'),
('SC Autoglobus SRL'),
('SC Hydromatic System SRL'),
('SC Build Your Career SRL'),
('SC Agro-Prod Maricom SRL'),
('SC Grosso SRL'),
('SC Tehno Concept SRL'),
('SC Reactiv Prod Com'),
('SC Quik n Shine'),
('SC Master Service SRL'),
('SC Konica Minolta'),
('SC Centrul Medical LIAD SRL'),
('Spitalul Clinic CF Timisoara'),
('Andex Import Export SRL'),
('Medimpact SA'),
('Minexfor SA'),
('Colimo SRl'),
('SIRV Caransebes'),
('Krasztel&Asociatii SRL'),
('FAB CCPM Impex SRL'),
('Udresu Nicolae II'),
('Maguay Computers SRL'),
('Eta 2U SRL'),
('EVW Holding SRL'),
('Topogecad SRL'),
('Union Protection SRl'),
('Royal Eurotrans SRL'),
('Vectra Eurolift Servicii'),
('SC JDD MINERAL CONSTRUCTII SRL'),
('SC Iprochim SA'),
('SCEngie Romania'),
('SC Vonrep SRL'),
('SC Four Media SRL'),
('SC Pro Air Clean Ecologic'),
('SC Con Metal SRL'),
('SC Alsting Timserv'),
('SC Instant International SRL'),
('Ink Technology'),
('Instant International SRL'),
('DDA Birotica'),
('Metabet CF SA'),
('Isal Tim SRL'),
('Almatar Trans SRL'),
('Maticom SRL'),
('Hidromold SRL'),
('Unior Tepid SRL'),
('Tim Ciclop SRL'),
('I&L Tehnoconsulting SRL'),
('Instant Internatinal'),
('Swing Trade'),
('Praetoria Construct'),
('AB Instal'),
('Grosso'),
('Reactiv Prod Com'),
('Delsitag Construct'),
('Tigers'),
('Prodesterv'),
('Electric Rail Proiect'),
('Iprochim'),
('SC ALTAMIRA IMPEX'),
('SC SETCAR SA'),
('SC ACA PROD SRL'),
('SC MOBTECO SRL'),
('SC COM LIBRIS SRL'),
('SPITAL CF SIMERIA'),
('SPITAL CF TIMISOARA'),
('CM LYAD ARAD'),
('SC Kober SRL'),
('SC Artego SRL'),
('SC Colimo SRL'),
('SC CEZ Vanzare'),
('T-Soft SRL'),
('SC Gecor SRL'),
('SC Minexfor'),
('SC UNION CO'),
('SC MANOLLY'),
('SC EURO BUSINES DIY-DOR'),
('SC MOXITRANS'),
('SC NIADA AUDITAXIEXPERT'),
('SC DIABAS BATA'),
('SC MATICOM'),
('OMNIASIG'),
('SC DIA TERMOINSTALWEST'),
('SC EVIDENT GRUP'),
('SC ELECTROENERGETICA'),
('SC COLIMO'),
('SC MSVM PROIECT'),
('SC ORTOS PROD'),
('SC ROMBIZ SRL'),
('VEST CONSTRUCT SRL'),
('CIT ONE SRL'),
('GAZ EST SA'),
('AQUAFIL SRL'),
('Union Co SRL'),
('SC ASTI International SRL'),
('SC Eta 2 U SRL'),
('SC Altex Romania'),
('SC Izolvest SRL'),
('SC Herflacris SRL'),
('SC A&A Electric SRL'),
('SC Renania Trade SRL'),
('SC NGM Company SRL'),
('SC Giacob SRL'),
('Progresul Profi Tools SRL'),
('Prodserv SRL'),
('Grosso SRL'),
('Eurodraft Proiect Design'),
('A&A Electric SRL'),
('Crucea Rosie Huneoara'),
('Proform Office'),
('Tonopex SRL'),
('Green Recycle SRL'),
('SC Industrial Cruman SRL'),
('SC Colimos SRL'),
('SC Chris Sketch Art SRL'),
('SC Maliteco SRL'),
('SC Aldosecurity SRL'),
('SC Kaeser Kompressoren SRL'),
('SC Bermi SRL'),
('SC Aer Comprestim SRL'),
('SC Medaconsult SRL'),
('SC Utilitar Fluid Construct SRL'),
('Grafopress SRL'),
('Property Advisory Group SRL'),
('Cert Sign SA'),
('Anghelus SRL'),
('Omniasig Viena Insurance Group'),
('CHOSSON PREST'),
('MAXIMA CONSTRUCT'),
('CRISTIAN PRODEXIM'),
('MATICOM'),
('ELASCO SOLUTIONS'),
('BIROMEDIA TRADING SRL'),
('ARTCIP CONSTIM SRL'),
('Kober SRL'),
('Niada Auditax Expert SRL'),
('Transblan Morosan SRL'),
('C&A Company Consulting'),
('Spital General CF Simeria'),
('SC AB Instal SRL'),
('SC UNION PROTECTION SRL'),
('CENTRUL MEDICAL LIAD SRL'),
('SC I&L TEHNOCONSULTING SRL'),
('MD Cons Plast'),
('VFM Intercom'),
('"PRISACARIU BUILD&CONSTRUCT SRL"'),
('Asirom'),
('SC Confortul Fil. Timisoara'),
('Artex Plus Disabilities'),
('SMZ IMPEX SRL'),
('VIMA SRL'),
('Udrescu Nicolae II'),
('SPIACT Cluj'),
('PROINSTAL SRL'),
('PRODUCTON SRL'),
('CEZ Vanzare SA'),
('Propt SA'),
('Alsting Timserv SRL'),
('Almatar Trans'),
('TINMAR ENERGY SA'),
('PR PROFI TOOLS'),
('TEHNOIND ELECTRIC'),
('MOXITRANS'),
('Prisacaru Build & Construct SRL'),
('Tanopex SRL'),
('SC Elitex'),
('SC Altamara'),
('SC Anghelus SRL'),
('Mirakl SRL'),
('Best Engine SRL'),
('SC Andy Star Impex SRL'),
('Global Sistem SRL'),
('Aer Comprestim SRL'),
('Cipimartex Distribution'),
('Gaz Est'),
('Kober'),
('Iscrom Evaluari'),
('Artego SRL'),
('Linde Gaz Romania'),
('Printopia SRL'),
('Stofe Buhusi'),
('Maticon'),
('NGN'),
('DIABAS BATA'),
('MIDA SOFT BUSINESS'),
('CM PROMED SRL'),
('Medicis SRL'),
('CM Liad'),
('Smart Consulting SRL'),
('FIDOX SRL'),
('SCAB INSTAL SRL'),
('MD CONSPLAST SRL'),
('SYSTEMTIM TECHNOLOGY SRL'),
('SC SMART CONSULTING'),
('LOAD SYS GROUP SRL'),
('UTI Bilding'),
('Maticon SRL'),
('Vest Construct'),
('SC Romanian Security Systems SRL'),
('sc Aer Comprestim'),
('IULIAN TRANSFOR SRL'),
('LINK BUILDER SRL'),
('PAMIRCO SRL'),
('TOTAL BUSINESS TEHNOLOGIS SRL'),
('Grup Isal KNG SRL'),
('Mapro Instal SRL'),
('Maxima Costruct SRL'),
('T-Soft'),
('Fran Tib Construction SRL'),
('Renault Comercial Romania'),
('Mirror Group SRL-D'),
('G4Cash SRL'),
('Almar Trans SRL'),
('"Moxitrans SRL in asoc. cu Tomy&Gaby Grup SRL"'),
('SELECT PRINT SRL'),
('Aninoasa SRL'),
('TELETIM SRL'),
('Consens SRL'),
('Devax Motors SRL'),
('Pienar Instal Construct SRL'),
('Tinmar Energy'),
('Manoprinting System SRL'),
('C&A Phoenix Art SRL'),
('PAV&RED CHEIA CONSTRUCT SRL'),
('ACTIV PROIECT SRL'),
('SC PRODESTERV SRL'),
('MD Cons Plast SRL'),
('Premier Energy Trading'),
('Centrul Medical Lied Arad'),
('SC SELTIS SOLUTIONS SRL'),
('ART CIP CONS TIM SRL'),
('SC CONFERMET INDUSTRIAL SRL'),
('DNS Birotitica SRL'),
('SC MEDICI''S SRL'),
('MIDA SOFT BUSINESS SRL'),
('SC 2NET COMPUTER SRL'),
('Incremental SRL'),
('ALWOOD SPEDITION SRL'),
('SC FAST BROKERS SRL'),
('MOXITRANS SRL'),
('SN NGM COMPANY SRL'),
('HERALD SRL'),
('FLEXIK AUTOMATION SRL'),
('REDTECH ELECTRONIC BRANDS SRL'),
('Petroutilaj 3DRD SRL'),
('POMIRCO'),
('SMART CONSULTING  SRL'),
('BN Business SRL'),
('Petre Ion Evaluari PFA'),
('Centru Medical Liad SRL'),
('SC TECHTEX SRL'),
('BCR'),
('Seda Invest'),
('Pyf Production Srl'),
('Romanian Security Systems'),
('SC NORTH WOOD EUROPE SRL'),
('BERMI GENERAL SRL'),
('ANINOASA TIM SRL'),
('BIOTA COM SRL'),
('REMARUL 13 FEB'),
('"URBAN UPGRADE ARCH. AND ENGINEERING"'),
('ABINSTAL SRL'),
('RELOC SA'),
('TEHNOIND ELECTRIC SRL'),
('WBW LOGISTIC SRL'),
('MANOPRINTING SYSTEM'),
('SC Almatar Trans SRL'),
('Petre Ion'),
('SC Bestengine'),
('SC GROUP ART CIP SERV SRL'),
('CAROMET SA'),
('Techtex SRL'),
('Dolex Com SRL'),
('Spinex Farm SRL'),
('Mirror Group Print SRL'),
('Impex Srl'),
('Misca SRL'),
('Depanero SRL'),
('Germrom Trading Import Export SRL'),
('BVG CONSULTING VISION SRL'),
('Mida Soft'),
('UTI MANAGEMENTS FACILITY'),
('TRUST CONSTRUCT MESTER'),
('Premier Energy Trading SRL'),
('Vestalpine Railway Systems Romania SA'),
('SC Metabet SA'),
('SC Oil Depol Service SRL'),
('Mecu Ion PFA'),
('"Urban Upgrade Architecture und Engineering"'),
('Utilitar Fluid Construct'),
('Setcar SA'),
('Electroputere VFU Pascani'),
('Inter Broker  Asigurare SRL'),
('NGM Company SRL'),
('Oslea Mutriam SRL'),
('AB INSTAL SRL'),
('IRECSON EVALUARI SRL'),
('SC Intel Broker de Asigurare SRL'),
('SC MD Cons Plast SRL'),
('SC NSM Intergrum SRL'),
('Sylc Con Trans SRL'),
('MSVM Proiect SRL'),
('Confermet Industrial SRL'),
('Petagon Business'),
('ELTECH'),
('T SOFT SRL'),
('"Asoc Valabile SRL si SC Valabile Smart SRL"'),
('SC LOAD SYS GROUP SRL'),
('BCR SA in asoc cu CIT ONE SRL'),
('SC Select Print SRL'),
('Romanian Security System'),
('SC North Woods Europe SRL'),
('Nitech SRL'),
('UTI Building'),
('Frangomi'),
('ARC Brasov'),
('Mataharias srl'),
('Union Protection'),
('SC Eon Energie Romania'),
('SC DEVAX MOTORS'),
('SC SMART CONSULTING SRL'),
('Aninoasa -Tim SRL'),
('C&A COMPANY CONSULTING SRL'),
('Centru Medical Misca SRL'),
('Danger SRL'),
('MODAVIL SRL'),
('North Wood  Europe SRL'),
('SC GRUP ART CIP SERV SRL'),
('RIK SRL'),
('SC METABET CF SA'),
('Incremental  SRL'),
('Oslea Mulvian'),
('Centrul Medical LIAD'),
('SC EXPERTUS SRL'),
('ASIROMINSURANCE GRUP'),
('WPS SECURITY GUARD SRL'),
('MIRROR GROUP PRINT SRL-D'),
('BALTUR SIB SRL'),
('CENTRUL MEDICAL MISCA  SRL'),
('SC TMG GUARD SRL'),
('BIT SECURE  SRL'),
('NOVA POWER & GAS SRL'),
('SC EUROSAFETY DISTRIBUTION'),
('SC PRO DT COM');

INSERT INTO furnizori (denumire_furnizor)
VALUES
  ('SC GUTMAN SERV SRL'),
  ('SC Amazon Cleaning SRL'),
  ('SC INFCON SA'),
  ('SC GALANO PREST SRL'),
  ('SC PUBLIX SRL'),
  ('SC Copyland Trading SRL'),
  ('SC CIVITAS PROIECTARE SRL'),
  ('SC TIMAREAN SRL'),
  ('SC BRIARIS IND SA'),
  ('SC VECTRAEUROLIFT SERVICE'),
  ('SC LECOM BIROTICA ARDEAL SRL'),
  ('ECO BIO MAGIC SRL'),
  ('SC WESTERN SECURITY SRL'),
  ('SC DD BIROTICA SRL'),
  ('SC ALTSTING TIMSERV SRL'),
  ('SC OK GURD SRL'),
  ('SPITALUL CLINIC CF CLUJ NAPOCA'),
  ('SC AQUASAR SA'),
  ('SC RAM SECURITY SERVIC SRL'),
  ('SC CONSTRUCTII FEROVIARE MURES SA'),
  ('SC JIFA SRL'),
  ('SC QUASAR SA'),
  ('G4S CASH SOLUTIONS SRL'),
  ('SC PAMIRCO SRL'),
  ('SC FIRE PROTECT SRL'),
  ('Spitalul CF Oradea'),
  ('SC FIDOX SRL'),
  ('SC ALDO SECRITY SRL'),
  ('SC FIRE &RESCUE SERVICES SRL'),
  ('Spitalul CF Cluj'),
  ('BANCPOST SA'),
  ('SC DELTASERV SRL'),
  ('SC TURKROM SA'),
  ('INCD INOE ICIA CLUJ'),
  ('ILIESCU FELICIA - PFA'),
  ('SC ROMOLD SECURITY SRL'),
  ('SPITALUL CLINIC CF CLUJ'),
  ('Spitalul Clinic CF Oradea'),
  ('ICIA CLUJ'),
  ('SC GALANO PREST'),
  ('MISADE COM SRL'),
  ('MESSER ROMANIA'),
  ('SC DIATOURS SRL'),
  ('SC RECYCLING PROD SRL'),
  ('SC DELTA SERV SRL'),
  ('SC AGEXIMCO SRL'),
  ('INCDO INOE'),
  ('SC CEZIANA STAR SRL'),
  ('BCR in asociere cu SC CIT ONE SRL'),
  ('SC SALMIR IMPEX SRL'),
  ('SOC. COOP. MESTESUGAREASCA DE GRAD I SOLIDARITATEA IASI'),
  ('SC RIVER TRADE SERVICES SRL'),
  ('SC INDUSTRY TRANSILVAN SRL'),
  ('SC TED PROTECT SRL'),
  ('SC LUKOIL LUBRICANTS EAST EUROPE SRL'),
  ('SC DRAGOSTAL SECURITY SRL'),
  ('Asocierea BCR in calitate de Lider de adociere si CIT One SRL in calitate de asociat'),
  ('Ilinca Gabriel P.F.A.'),
  ('Lukoil Lubricants East Eurpoe SRL'),
  ('Asocierea: S.C. Rino Guard SRL S.C. Dragostal Security SRL S.C. Dragostal Titan Guard SRL'),
  ('SC Ecocranes Romania SRL'),
  ('Banca Comercială Română'),
  ('INCDO INOE 2000, Filiala Institutul de Cercetări pentru Instrumentație Analitică Cluj-Napoca'),
  ('SC Flyng Impex SRL'),
  ('SC Man Protecțion SRL'),
  ('SC Mariposa AMC ART SRL'),
  ('SC Milano Papetărie SRL'),
  ('SC Grafopress SRL'),
  ('SC M.A. Cristina SRL'),
  ('SC Lukoil Lubricants East Eurpoe SRL'),
  ('SC River Trade & Services SRL'),
  ('SPITALUL GENERAL CF Brasov'),
  ('SC MINEXFOR SA Deva'),
  ('S.C. VALDORIS S.R.L. Brașov'),
  ('S.C 2NET COMPUTER S.R.L. Brașov'),
  ('S.C. T-SOFT S.R.L. Brașov'),
  ('SC SGPI SECURITY FORCE SRL Bucuresti'),
  ('SC ASTRU GRUP SRL Braila'),
  ('SC CICLOPS SECURITY SRL Sibiu'),
  ('SC BRESCIA PROD COM SRL Danesti, Gorj'),
  ('SC ALDO SECURITY SRL Bucuresti'),
  ('SC INTERMEDICA HS SRL Sibiu'),
  ('SC MIRROR GROUP PRINT SRL-D Craiova'),
  ('SC DNS BIROTICA SRL Bucuresti'),
  ('SC ARCON DISTRIBUTIE SRL Bucuresti'),
  ('SC TIBOB TRANS SRL Brasov'),
  ('SC FRIREP SA Pascani'),
  ('SC CONSTRUCTII FEROVIARE MURES Tg. Mures'),
  ('BCR SA Bucuresti'),
  ('SC TAPEL SRL Sibiu'),
  ('SC RELOC SA Craiova'),
  ('SC SEDA INVEST SRL Brasov'),
  ('SC EMROM AVIATION SRL Cornetu Ilfov'),
  ('SC BRIGHT ENGINEERING-RO SRL Bucuresti'),
  ('SC LINDE GAG ROMANIA SRL Timisoara'),
  ('SC TOTAL BUSINESS TEHNOLOGIES SRL Chiajna Ilfov'),
  ('SC EVIDENT GROUP SRL Bucuresti'),
  ('SC VULCOM SRL Sanpetru Brasov'),
  ('SC SEDA INVEST SRL Prejmer Brasov'),
  ('PODAR GABRIEL PFA Brasov'),
  ('SCLEMINGS SRL Constanta'),
  ('SC ROMAER-PRO SRL Maramures'),
  ('FAST BROKERS -BROKER ASIGURARE REASIGURARE SRL Bucuresti'),
  ('SC VIGRA MARKETING & SERVICES SRL'),
  ('SC ASTII INTERNATIONAL SRL'),
  ('SC BANGSONIC SRL'),
  ('SC PRO TEHNIC SRL'),
  ('SC DACONA SRL'),
  ('SC BRUDER LEISTUNG SRL'),
  ('S.C. TEKTRON S.R.L.'),
  ('S.C. INSTALCAM CONSTRUCT S.R.L.'),
  ('S.C. THERMOFIX FACILITY SERVICES S.R.L.'),
  ('S.C. ZO TRANS S.R.L.'),
  ('S.C. RADACINI MOTORS S.R.L.'),
  ('S.C. ASTRU GRUP S.R.L.'),
  ('S.C. LICON S.R.L.'),
  ('S.C. BREAK SISTEMS S.R.L.'),
  ('S.C. ADETRANS SRL'),
  ('SC BRASTING SRL'),
  ('S.C. LACATUS SAMUEL CONSTRUCT S.R.L.'),
  ('S.C. TEMAD CO S.R.L.'),
  ('S.C. BIROTIC S.R.L.'),
  ('CENTRUL MEDICAL INTERMEDICA'),
  ('S.C. TOTAL CONTROL S.R.L.'),
  ('S.C. ROMSYSTEMS S.R.L.'),
  ('S.C. MEDA CONSULT S.R.L.'),
  ('S.C. TIBOB TRANS S.R.L.'),
  ('S.C. C&A PHOENIX ART S.R.L.'),
  ('S.C. NGM COMPANY S.R.L.'),
  ('S.C. NEW MOB EXPANSION S.R.L.'),
  ('S.C. DRAGOSTAL SECURITY S.R.L.'),
  ('S.C. MIRROR GROUP PRINT SRL-D'),
  ('S.C. NOVATEX S.R.L.'),
  ('S.C. GECOR S.R.L.'),
  ('S.C. COTRACO ROM S.R.L.'),
  ('S.C. DAMIPROD S.R.L.'),
  ('S.C. FRIREP S.A.'),
  ('S.C. POLYGON TRADING S.R.L.'),
  ('S.C VULCOM S.R.L.'),
  ('S.C. BANCA COMERCIALA ROMANA S.A.'),
  ('S.C. DELTA MACHINE S.R.L.'),
  ('S.C. SEDA INVEST S.R.L'),
  ('S.C. GLOBAL SISTEM S.R.L.'),
  ('SC SIRIUS SRL SIBIU'),
  ('Asigurarea Romaneasca Asirom Vienna Insurance Group SA'),
  ('SC ADAM EL TENSO SRL'),
  ('SC MISADE SRL'),
  ('SC MISADE COM SRL'),
  ('SC EDNA CONSTRUCT 2005 SRL'),
  ('SC MEDIUPUR SERV SRL'),
  ('SC LUS AUTO SERVICESRL'),
  ('SC NIKRA IMPEX SRL'),
  ('SC ELMAS SRL'),
  ('SC ENERGO METR SRL'),
  ('SC TRANS BLAN MOROSAN SRL'),
  ('SC ASTRU GRUP SRL'),
  ('SC EDNA CONSTRUCT 2015 SRL'),
  ('SC EVALFIX TEHNIC SRL'),
  ('SC CENTRUL MEDICAL UNIREA SRL'),
  ('SC GRUP SOLUTII EXPERTE SRL'),
  ('SC FIRE & RESCUE SERVICES SRL'),
  ('SC TIBOB TRANS SRL'),
  ('SC KYNITA SRL'),
  ('SC MANOPRINTING SYSTEM SRL'),
  ('SC REMARUL 16 FEBRUARIE SA'),
  ('SC BN BUSSINESS SRL'),
  ('SC ABCONY SERV SRL'),
  ('SC MIRROR GROUP PRINT SRL-D'),
  ('SC NAGUMA MEDICAL SUPPLY SRL'),
  ('BANCA COMERCIALA ROMANA (BCR) SA -lider de asociere CIT ONE SA'),
  ('SC VULCOM SRL'),
  ('SC PRIMAGRA SRL'),
  ('SC FRIREP SA'),
  ('SC NOVA LIBRIS IMPEX SRL'),
  ('SC CLEAN OTTER SRL'),
  ('SC INTER BROKER DE ASIGURARE SRL'),
  ('SC ELECTROTERMOMETRIA SRL'),
  ('SC LUS AUTO SERVICE SRL (Asociere SC TUDUMI SRL)'),
  ('SC MEDICA M3 COMEXIM SRL'),
  ('SC PYF PRODUCTION SRL'),
  ('SC ANCORA COM'),
  ('SC SEILAND SRL'),
  ('SC SHORTCUT SRL'),
  ('CENTRUL MEDICAL UNIREA'),
  ('SC SITIGUARD SRL'),
  ('MECU ION P.F.A'),
  ('SC ARMOS SERVICES SRL'),
  ('SC D&G GROUP SRL'),
  ('ASOCIERE BCR SA si CIT ONE SA'),
  ('SC EUROPROTECT SAFETY SRL'),
  ('SC SECURITY CONSULTING SERVICES SRL'),
  ('SC T SOFT SRL'),
  ('SC DAMIPROD SRL'),
  ('SC PSG ONE SRL'),
  ('SC MOBCOMAND SRL'),
  ('SC SICARO SRL'),
  ('SC ANCORA COM SRL'),
  ('SC MINET CONF SRL'),
  ('SC ROTHER RO SRL'),
  ('UNIFAST SRL'),
  ('IT HERO TECHNOLOGIES'),
  ('CONSTRUCȚII FEROVIARE Mureș SA'),
  ('RELOC SA Craiova'),
  ('RTC PROFFICE EXPERIENCE SA'),
  ('ATLAS PNEUMATIC SRL'),
  ('EURO TOPFER SRL'),
  ('VULCOM SRL'),
  ('JULIEN PROTECT SRL'),
  ('TIBOB TRANS SRL'),
  ('MAXMAN SRL'),
  ('BANCA COMERCIALA ROMANA (BCR) SA și CIT ONE SA (subcontractant)'),
  ('Societatea Asigurarea Romaneasca- ASIROM VIENNA INSURANCE GROUP SA'),
  ('CARANDA BATERII SRL'),
  ('SC T-SOFT SRL Brașov'),
  ('SC MIRROR GROUP PRINT SRL Craiova'),
  ('SC RIU GRANDE PROJECT SRL'),
  ('SC ATLAS PNEUMATIC SRL'),
  ('SC SPRINTER 2000 SA'),
  ('Avigall SRL Iasi'),
  ('Cosmin Company SRL Iasi'),
  ('Euroserv Clean SRL Bucuresti'),
  ('SC Avigall SRL Iaşi'),
  ('SC Shatter SRL Iaşi'),
('SC Esc Servicii Curăţenie SRL Bucureşti'),
('SC Diacostampet SRL Petrila'),
('SC Cosmin Company SRL Iaşi'),
('SC Elite Tuning Service SRL Iași'),
('SC Romil Service SRL Iași'),
('SC Fortransor Lemn SRL Ştiubeni'),
('SC Adi Center SRL Vatra Dornei'),
('SC Euro Siam Thai SRL Slanic Moldova'),
('SC Inscom SA Fălticeni'),
('SC Condep SRL Onești'),
('Isis Comprest SRL Barlad'),
('SC Universal Construct Impex SRL Iasi'),
('SC Rama Clau SRL Miercurea Ciuc'),
('SC Ghenuţa SRL Iaşi'),
('SC Evident Group SRL Bucureşti'),
('SC Ortos Prod SRL Zalău'),
('Centrul de pregătire şi perfecţionare profesională al Inspecţiei muncii Botoşani'),
('Iaşi Sting Grup SRL Iaşi'),
('Euro Forest Exim Tg. Neamţ'),
('Certsign SA'),
('Media Rom Grup SRL Iasi'),
('Euseb SRL Tg. Neamt'),
('Varcom Business SRL Bucuresti'),
('CNCF ”CFR” SA - Sucursala Regională CF Iași'),
('Fontana Fasteners SRL'),
('Rama Clau SRL Miercurea Ciuc'),
('SCM de gradul 1 Solidaritatea Iași'),
('Vertical Trend SRL'),
('Trans-Blan Moroşan SRL'),
('Alimar Oem SRL'),
('Texer Service Co SRL'),
('PFA Romeo Costache'),
('Aca Divi Distribution Chişinău SRL Iaşi'),
('Ghenuţa SRL'),
('Angels SRL'),
('Aca Prod Actual SRL'),
('Util SPC SRL Giurgiu'),
('3D Arhigrup SRL Iasi'),
('e-Birotik SRL Suceava'),
('Trocri Impex SRL Bacau'),
('Ati Motors Holding SRL'),
('Novus SRL Constanta'),
('Planiterm SRL Suceava'),
('Global Eco Center SRL Iasi'),
('RTH ProConstruct SRL Bucuresti'),
('Softronic SRL Craiova'),
('International Rail Transport Timişoara SRL Timişoara'),
('Spitalul Clinic CF Iaşi'),
('CNCF ”CFR” SA Sucursala Regională de Căi Ferate Iași'),
('Evident Group SRL Bucureşti'),
('Inscom SA Fălticeni'),
('Electrificare CFR Sucursala Electrificare Iasi'),
('Novatech SRL Bucuresti'),
('Hidromold'),
('Union Co Cluj-Napoca'),
('Ges Forces SRL'),
('Acadivi Distribution Chişinau SRL'),
('Businessfan SRL'),
('Anti-Pan-Con SRL Bacau'),
('Arobs Transilvania Software SA Cluj-Napoca'),
('Topomarcad SRL'),
('Ghenuta SRL'),
('Microenerg SRL Bacau'),
('Albo-Citi SRL Iasi'),
('Fast Brokers - Broker de Asigurare - Reasigurare SRL Bucuresti'),
('Tipografia Prod Com SRL Tg. Jiu'),
('Digital Security Systems SRL Ipotesti'),
('Bonello proiect SRL Dolhasca'),
('Rama Clau SRL Miercurea-Ciuc'),
('Trust Construct Cipriany SRL'),
('PFA Oprea Vasilica-Florinel'),
('Seda Invest SRL Brasov'),
('Hanex SRL Bucuresti'),
('Trans-Blan Morosan SRL'),
('Medimpact SA Medias'),
('Apa Vital SA Iasi'),
('Eurotech SRL Iasi'),
('DNS Birotica Bucuresti'),
('Petrica Group SRL Petricani Neamt'),
('Oprea Vasilica Florinel PFA'),
('Voestalpine Vae Apcarom SA'),
('Acadivi Distribution Chisinau SRL Iasi'),
('PFA Stoica Romeo'),
('NGN Company Navodari'),
('Protect Styl Industry SRL'),
('SCM Grad 1 Solidaritatea Iasi'),
('Art Ego group SRL'),
('Ekipa SRL Suceava'),
('Molid Tehnic Service SRL Iasi'),
('Metronom Moldova SRL'),
('Vectra Eurolift Service'),
('Rongal SRL Iasi'),
('General Tehnic SRL'),
('Iamsatis SRL Iasi'),
('PST Appraisal SRL Bucuresti'),
('Prima Construct SRL'),
('GS Training Serv SRL'),
('Nicolamar SRL'),
('Aldo Security SRL Bucuresti'),
('Frirep SA Pascani'),
('T-Soft SRL Brasov'),
('Eva Nouvel SRL Iasi'),
('Universal Wash Limited SRL'),
('Mon-Gam SRL Suceava'),
('Fast Brokers - Broker de Asigurare - Reasigurare SRL'),
('Forgaci Ovidiu-Ionel PFA'),
('Fire&Rescue Services SRL'),
('Vic Insero SRL'),
('Real Protection SRL'),
('Rama Clau SRL'),
('Messystech SRL'),
('CNCF ”CFR” SRCF Iasi'),
('Elerom SA'),
('Beny Alex SRL in asociere cu JVI Impex SRL'),
('PFA Zbarnea Gh. Niculina'),
('Vertical Trend SRL Valea Lupului, Iasi'),
('Vadova SRL Valcea'),
('Giacob SRL Bistrita-Nasaud'),
('Renania Trade SRL'),
('Izvocolor 92 Prod SRL'),
('Unitar Proiect TDA SRL Bucuresti'),
('Businessfan SRL - Sadova'),
('Adam El Tenso SRL - Tg Mures'),
('Real Protection Guard SRL - Suceava'),
('Heavy Duty Construct SRL Iasi'),
('BCR SA'),
('Novatech SRL'),
('Arobs Transilvania Software SA Cluj'),
('Safe SRL Ilfov'),
('Almatar Trans SRL Buzau'),
('Metronom Moldova SRL Iasi'),
('Curatatoria Omniclean SRL Iasi'),
('Simosilflor SRL'),
('Tehmin-Brasov SRL'),
('Profesional Security Division SRL'),
('IPS Grup SRL Piatra Neamt'),
('Mar-Ina Prodprest SRL'),
('Evident Group SRL București'),
('ICPE Saerp SA'),
('Rimoldo Consulting Group'),
('Trust Construct Proiect SRL');

INSERT INTO furnizori (denumire_furnizor)
VALUES
  ('Proficons Project SRL'),
  ('Osiris Dunibema SRL'),
  ('Termo Asist'),
  ('Biservconstructfab SRL'),
  ('Axel Telecom& Technologies'),
  ('Mobilis SRL'),
  ('Eximod Pneumatic Expert SRL'),
  ('Rulexim SRL'),
  ('Neohabitat-Office SRL'),
  ('Arobs Transilvania Software SA'),
  ('Total Control SRL Bucuresti'),
  ('Monoradas SRL'),
  ('Romanian Security Systems SRL'),
  ('Prauco AMV Craft SRL'),
  ('Eurospeed SRL'),
  ('Safe SRL'),
  ('Fast Brokers - Broker de Asigurare Reasigurare'),
  ('Dragostal Security SRL'),
  ('Asirom SA'),
  ('Mediu Pur Services SRL cu subcontractant SC Tehnica Mobila Oil SRL'),
  ('PIM SRL'),
  ('Damiena SRL'),
  ('Romold Security SRL'),
  ('Proiect Instal SRL'),
  ('Global Business Development &Construction ASG SRL'),
  ('Armos Service SRL'),
  ('Romlider evaluari imobiliare SRL'),
  ('Cocktail Security Agency SRL'),
  ('Termo Asist SRL'),
  ('Curatatoria Omniclean SRL'),
  ('Protehnica Export SRL'),
  ('Asti International SRL'),
  ('Romanian Security System SRL'),
  ('Gamiatricos Com SRL'),
  ('Societatea Evaluare si Expertiza Judiciara Olaru si Asociatii SRL'),
  ('Green Atlantic SRL'),
  ('Iasisting Group SRL'),
  ('Apavital SA'),
  ('Universal Service SRL'),
  ('Artoil SRL'),
  ('Barna Ghe Alexandra Intreprindere Individuala'),
  ('Voestalpine Railway Systems Romania SA'),
  ('Dinalucri SRL'),
  ('Sheriff Guard Protection SRL'),
  ('Adam El Tenso SRL'),
  ('Micro World SRL'),
  ('Spiact Cluj SA'),
  ('Salmir Impex SRL'),
  ('Universal Construct Business SRL'),
  ('Ohsas Expert SRL'),
  ('Burkharo International SRL'),
  ('Gia Sistem SRL'),
  ('Universitatea Tehnica "Ghe. Asachi" Iasi'),
  ('Rino Guard SRL in asociere cu Dragostal Security SRL'),
  ('Construct Maia PVL'),
  ('PFA Cobzariu Eduard Sorin'),
  ('Protect Distribution SRL'),
  ('Truck&Bus Assistance SRL'),
  ('Protect Colector SRL'),
  ('Telecomunicatii CFR SA'),
  ('Top Pram Electric SRL'),
  ('SC 11 Perfect International SRL'),
  ('Dragostal Titan Guard SRL cu subcontractant Nord-Est Security Force SRL'),
  ('Envi International SRL'),
  ('Tal Tedom SRL'),
  ('Deratoinvest SRL'),
  ('SC GHENUTA SRL IASI'),
  ('SC ESC SERVICII CURATENIE SRL BUCURESTI'),
  ('INCD -ECOIND BUCURESTI'),
  ('SC UNION CO CLUJ NAPOCA'),
  ('SC GROSSO SRL BRASOV'),
  ('SC Manoprinting System SRL Oradea'),
  ('SC Rompetrol Downstream SRL Bucuresti'),
  ('SC RAMA CLAU MIERCUREA CIUC'),
  ('SC Ned Com SRL Constanta'),
  ('SC CONDEP SRL ONESTI'),
  ('SC MAR-INA PRODPREST SRL GALATI'),
  ('S.C. SIMANDREA S.R.L. Dej'),
  ('S.C SEDA INVEST S.R.L. Brasov'),
  ('S.C. NGM COMPANY S.R.L. Navodari'),
  ('S.C. TOTAL PROTECTOR S.R.L. Popesti-Leordeni'),
  ('S.C. PUBLIX S.R.L. CLUJ NAPOCA'),
  ('ASOCIATIA "APH SPORTING CLUB" - Sectia Speranta si Vis Galati'),
  ('S.C. RAMA CLAU S.R.L. Miercurea-Ciuc'),
  ('S.C. GROSSO S.R.L Brasov'),
  ('ASOCIATIA DREPTURI EGALE PENTRU TOTI - Sectia COMADEPT Galati'),
  ('S.C. GHENUTA S.R.L. Iasi'),
  ('S.C. MAR-INA PRODPREST S.R.L. Galati'),
  ('S.C.NED COM S.R.L. Constata'),
  ('S.C. DALPRO SERVICE S.R.L. Bucuresti'),
  ('S.C. GROSSO S.R.L. Brasov'),
  ('S.C ROVAL PRINT S.R.L. Galati'),
  ('S.C. ASTRU GRUP S.R.L. Braila'),
  ('S.C. ACA PROD ACTUAL S.R.L. Constanta'),
  ('S.C. MOBILIS S.R.L. Iasi'),
  ('INCD - ECOIND Bucuresti'),
  ('S.C. ALIMAR OEM Voluntari, Ilfov'),
  ('S.C. GRAPHODOCS S..R.L. Cluj Napoca'),
  ('S.C BERMI GENERAL S.R.L. Pitesti'),
  ('S.C.RAMA CLAU S.R.L. Miercurea Ciuc'),
  ('S.C. CARANDA BATERII S.R.L. Bucuresti'),
  ('S.C. BRESCIA PROD COM S.R.L. Danesti, Gorj'),
  ('S.C. FLYNG IMPEX S.R.L. Baia Mare'),
  ('S.C. ACA PROD ACTUAL S.R.L Constanta'),
  ('S.C.BERMI GENERAL S.R.L. Pitesti'),
  ('S.C. GAZINSTAL ENERGY S.R.L. Buzău'),
  ('S.C. CRISTAN PRODEXIM S.R.L. Chitila, jud. Ilfov'),
  ('S.C. NECESAR PROD S.R.L. Brăila'),
  ('S.C. TOTAL PROTECTOR S.R.L. Popeşti Leordeni, jud. Ilfov'),
  ('S.C. ROYAL SERVICE S.R.L. Tulcea'),
  ('S.C. DDA BIROTICA OFFICE S.R.L. Bucuresti'),
  ('S.C. TEPACOS COMPANY S.R.L. Timisoara'),
  ('S.C. G4S CASH SOLUTIONS S.R.L. Bucuresti'),
  ('S.C. CONSTRUCTII COMPLEXE BUZAU S.A.'),
  ('UNION CO S.R.L. Cluj-Napoca'),
  ('ASOCIAŢIEI EURODEZVOLTARE GALAŢI'),
  ('MAR-INA PRODPREST S.R.L. Galaţi'),
  ('TURKROM S.A. Focşani'),
  ('TRAS-BLAN MOROSAN S.R.L. Lumina, jud. Constanţa'),
  ('S.C. PROIECT LG&CF S.R.L. Constanţa'),
  ('IPROEX ENERGY MANAGEMENT S.R.L. Bucuresti'),
  ('FLYNG IMPEX S.R.L. Baia Mare'),
  ('EVIDENT GROUP S.R.L. Bucuresti'),
  ('ANDY STAR IMPEX S.R.L. Targoviste'),
  ('MIRROR GROUP S.R.L.-D Craiova'),
  ('REACTIV PROD COM S.R.L. Baia Mare'),
  ('TEPACOS COMPANY S.R.L. Timisoara'),
  ('BERMI GENERAL S.R.L. Pitesti'),
  ('TURKROM S.A. Focsani'),
  ('ACA PROD ACTUAL S.R.L. Constanta'),
  ('SEDA-INVEST S.R.L. Brasov'),
  ('METABET CF S.A. Pitesti'),
  ('ANDRAG REIGOS S.R.L. Cuca, jud. Arges'),
  ('ASTRU GRUP S.R.L Braila'),
  ('BANCPOST S.A. Bucuresti'),
  ('KRASZTEL&ASOCIATII S.R.L. Toplita'),
  ('MANOPRINTING SYSTEM S.R.L. Oradea'),
  ('ALDO SECURITY S.R.L. Bucuresti'),
  ('TRANS-BLAN MOROSAN S.R.L. Lumina, jud. Constanta'),
  ('SANAVITA AM MEDICAL POIN S.R.L. Galati'),
  ('COMPANIA CONSTRUCTII FEROVIARE S.A. Campulung Moldovenesc'),
  ('ANDRONIU G.IULIAN-COSMIN- EXPERT EVALUATOR Braila'),
  ('ROTOTRANS S.R.L. Galati'),
  ('GROUPE EUROVEST INTERNATIONAL S.R.L. Constanta'),
  ('MINEXFOR S.A. Deva'),
  ('GROSSO S.R.L. Brasov'),
  ('BIRO-MEDIA TRADING S.R.L. Bucuresti'),
  ('CRISTAN PRODEXIM S.R.L. Chitila'),
  ('DIRALITEX S.RL. Bezdead, jud. Dambovita'),
  ('LENOX PROD S.R.L. Bucuresti'),
  ('TOPO ADWG S.R.L. Straoane, jud. Vrancea'),
  ('CIPIMARTEX DISTRIBUTION S.R.L. Bucuresti'),
  ('TERMOINSTAL PROIECT S.R.L. Focsani'),
  ('INEDIT CLEAN TOTAL S.R.L. Catrlu, jud. Ilfov'),
  ('BANCA COMERCIALA ROMANA S.A.'),
  ('COMPANIA CONSTRUCŢII FEROVIARE S.A. Iaşi'),
  ('RELOC S.A. Craiova'),
  ('MEXIMPEX S.R.L. București'),
  ('S.C. PROFICONS PROJECT S.R.L. – Botoșani'),
  ('ACTIV PROIECT S.R.L. Bucureşti'),
  ('SANAVITA AM MEDICAL POINT S.R.L. Galaţi'),
  ('MEDIMPACT S.A. Mediaș'),
  ('DINALUCRI S.R.L. Galați'),
  ('BRESCIA PRODCOM S.R.L. Danesti, jud. Gorj'),
  ('ARCA MONDO CHIM S.R.L. Bucuresti'),
  ('GLOBAL SISTEM S.R.L. Iasi'),
  ('ANDRAG REIGOS S.R.L. com. Cuca, jud. Arges'),
  ('IRECSON EVALUARI S.R.L. Bucuresti'),
  ('BIROTICA CITY GROUP S.R.L. Galati'),
  ('LINDE GAZ ROMANIA S.R.L. Timisoara'),
  ('COVALSAGA ELECTRIC S.R.L. Galati'),
  ('ASTI INTERNATIONAL S.R.L. Bucuresti'),
  ('MIDA SOFT BUSINESS S.R.L. Bucuresti'),
  ('BCR ROMANIA'),
  ('DIRALITEX COM S.R.L. Bezdead'),
  ('ADA CONSTRUCT2007 S.R.L. Buzau'),
  ('PYF PRODUCTION S.R.L. Craiova'),
  ('ACTIV PROIECT S.R.L. Bucuresti'),
  ('RENAULT COMERCIAL ROUMANIE S.R.L. Bucuresti prin imputernicit APAN S.R.L. Braila'),
  ('MEDIMPACT S.A. Medias'),
  ('SANAVITA AM MEDICAL POINT S.R.L. Galati'),
  ('TRANS BLAN MOTOSAN S.R.L. Lumina, jud. Constanta'),
  ('ARTEGO S.A. Tg. Jiu'),
  ('ELECTRO HIDRAULIC MOTORS GRUP S.R.L. Bucuresti'),
  ('CHROME COPUTERS S.R.L. Bucuresti'),
  ('COMPANIA CONSTRUCȚII FEROVIARE SA Iași'),
  ('BIT TECHNOLOGIES S.R.L. Râmnicu Vâlcea'),
  ('VAE APCAROM S.A. Buzău'),
  ('COVALSAGA ELECTRIC S.R.L. Galaţi'),
  ('EUROSTING AAW INDUSTRY Buzau'),
  ('COVALSAGA S.R.L. Galaţi'),
  ('C&C PREVENT S.R.L. Galati'),
  ('SEDA INVEST SR.L. Brasov'),
  ('BIOSOL PSI S.R.L. Ploiesti'),
  ('DIRALITEX COM S.R.L.'),
('ROPECO BUCURESTI S.R.L. Chiajna'),
('VOESTALPINE RAILWAY SYSTEM ROMANIA S.A. Buzau'),
('REM-ROX S.R.L. Slatina'),
('CONTRANS IMPEX S.R.L. Drobeta-Turnu Severin'),
('TEMAD CO S.R.L. Brasov'),
('01 PROCONSTRUCTO TOP SERVICES GROUP S.R.L. Bucuresti'),
('RHINO SAFETY S.R.L. Bacau'),
('NIADA AUDITAX EXPERT S.R.L. com. Surani, jud. Prahova'),
('COVALSAGA S.R.L. Galati'),
('EUROSTING AAW INDUSTRY S.R.L. Buzau'),
('YORK FARM S.R.L. Bucuresti'),
('PLUSTER PROTECT S.R.L. Alba Iulia'),
('TRANSLIMA S.R.L. Galati'),
('PRODIVEX S.R.L. Sibiu'),
('REGIO METRO CERT S.R.L. Pielesti, jud. Dolj'),
('METROREAL S.R.L. Pielesti, jud. Dolj'),
('UTI FACILITY MANAGEMENT S.A. Otopeni, jud. Ilfov'),
('ARMOS SERVICES S.R.L. Tg.-Mureș'),
('IRECSON EVALUĂRI S.R.L. Bucureşti'),
('ARTEGO S.A. Târgu-Jiu'),
('BANCA COMERCIALĂ ROMÂNĂ (Lider), CIT ONE S.A. București (Asociat)'),
('CONSTRUCTII COMPLEXE S.A. BUZĂU'),
('BISERVCONSTRUCTFAB S.R.L. Prahova'),
('INTERBABIS S.R.L. Brasov'),
('Asocierea: CBC HALE S.R.L. Botoşani (Lider), RA&CO S.R.L. Craiova (Asociat)'),
('VOESTALPINE RAILWAY SYSTEM ROMÂNIA S.A.'),
('VIKMAR SERV S.R.L. Bacau'),
('TIPOHAV S.R.L. Galaţi'),
('D&G GROUP S.R.L. Călăraşi'),
('ARTEGO S.A. Tg.Jiu'),
('BIOSOL PSI S.R.L. Ploiești'),
('RAMA CLAU S.R.L. Miercurea Ciuc'),
('ANDA CONFECTION CAMI S.R.L. Pucioasa'),
('MEDA CONSULT S.R.L. Târgovişte'),
('DNS BIROTICA S.R.L. Bucureşti'),
('Evaluare și Expertiză Judiciară Olaru și Asociații SRL București'),
('RIVER TRADE & SERVICES S.R.L. Cluj Napoca'),
('VEST INSTAL MS.R.L. Calarasi'),
('VOESTALPINE RAILWAY SYSTEM ROMANIA S.A.'),
('TAL TEDOM S.R.L. Medgidia'),
('CARANDA BATERII S.R.L. București'),
('SCM LEMN METAL Reghin'),
('MODAVIL S.R.L. Ramnicu Valcea'),
('Asocierea: CONSTRUCTII FEROVIARE GALATI S.A. (ofertant lider) CRIDEN CONSTRUCT S.R.L. Galati (ofertant asociat)'),
('Asocierea: BANCA COMERCIALĂ ROMÂNĂ (ofertant lider), CIT ONE S.A. Bucureşti (ofertant asociat)'),
('SANAVITA AM MEDICAL POINT S.R.L. Galaţi (ofertant lider), Cabinet Individual de Psihologie Lupascu Rodica (subcontractant)'),
('PANCRONEX S.A. Braila'),
('PLUSTER PROTECT S.R.L. Alba Iulia – Iulia'),
('EVIDENT GROUP S.R.L. București'),
('DOLEX COM S.R.L. Rm.Vâlcea'),
('TIPOGRAFIA MARIA D.M. S.R.L. Galaţi'),
('ALTEX ROMÂNIA S.R.L. Voluntari, jud. Ilfov'),
('UNION PROTECTION SRL Cluj-Napoca'),
('Infinity M&S Management SRL Constanta'),
('Departamentul ITC Ceteras SRL Tg.Mureș'),
('ROMAX EXPORTIMPORT S.R.L. Bucuresti'),
('FAST BROKERS - Broker de Asigurare Bucuresti'),
('TAPEL S.R.L. Sibiu'),
('REGIO METRO CERT S.R.L. Piliesti, Dolj'),
('SC 11 FRANGERS SRL'),
('SC ESC SERVICII CURATENIE SRL'),
('SC SIM ELDI SRL'),
('SC EURO CONSTRUCT SA'),
('SC MIRA SISTEM GRUP SRL'),
('SC RIK SRL'),
('SC SAVE & SELF SECURITY SRL'),
('SC MELUSTI SONIC SRL'),
('NS COPIERS SRL'),
('SC CLIMECO SRL'),
('SC FAVORIT SA'),
('SC SAVE & SELF COMPANY GUARD SRL'),
('SC TINMAR IND SA'),
('SC ROMNATIONAL SRL'),
('SC ZERG SECURITY SRL'),
('SC FERERO STAR SRL'),
('SC GROUPE EUROVEST INTERNATIONAL SRL'),
('SC AXEL TELECOM GRUP SRL'),
('SC ARCONS SRL'),
('SC FLAMINGO INTERNATIONAL CO SRL'),
('SC ASTRU GRUP SRL SC EURO CONSTRUCT SA'),
('SC NEI DIVIZIA SE SECURITATE SRL'),
('SC VIREO ENVIROCONSULT SRL'),
('SC SAVE& SELF COMPANY GUARD SRL'),
('SC EURO PARTS SERVICES SRL'),
('SC FOR GUARD PROFESSIONAL SRL'),
('SC TRADITIONAL ECO SRL'),
('SC MEGACONSTRUCT SA'),
('SC SERVICE ELECTROCASNICA SRL'),
('SC ABC MEDICAL CENTER SRL');

INSERT INTO furnizori (denumire_furnizor)
VALUES
	('PFA HARALAMBIE GHEORGHE'),
    ('SC SAMTEC SRL'),
    ('SC BANC POST SA'),
    ('SC MASCHINENBAU INDUSTRY SRL'),
    ('SC PROIECT LG&CF SRL'),
    ('SC FIVE HOLDING SA'),
    ('SC SOFTMET SRL'),
    ('SC ANTEOS RISK SRL'),
    ('SC CLIMAVENTPRO SRL'),
    ('SC NS COPIERS SRL'),
    ('SC CNCFR SA- SRCF CTA'),
    ('SC SETCONSTRUCT SRL'),
    ('SC ANDROMEDA SERV SRL'),
    ('SC TIRIAC AUTO SRL'),
    ('SC FORTE SYSTEMS SRL'),
    ('SC KOKKAI COMIMPEX SRL'),
    ('SC ONE STAR SECURITY SRL'),
    ('SC KRASZTEL& ASOCIATII SRL'),
    ('SC ZIUA TOMIS SRL'),
    ('SC BIRO-MEDIA SRL'),
    ('SC BANCA COMERCIALA ROMANA SA'),
    ('SC ELECTRIC TIMEING 3A SRL- D'),
    ('SC AVANGARDE BUSSINESS GROUP SRL'),
    ('SC METRON SERV SRL'),
    ('SC BOTE INSTAL SRL'),
    ('SC TAPEL SRL'),
    ('CN CFR -SRCF Constanta'),
    ('PFA DUMITRU I. MARIANA'),
    ('SC MOB&IUS SA'),
    ('SC COSMOPOL SECURITY SERVICE SRL'),
    ('SC ROMBIZ IMPEX SRL'),
    ('SC COMAT SA'),
    ('SC GMB COMPUTERS SRL'),
    ('SC BCR SA'),
    ('SC DOLAS ECOTRADE SRL'),
    ('SC TINMAR ENERGY SRL'),
    ('SC LINDE GAZ ROMANIA SRL'),
    ('SC CNCIR SA'),
    ('SC FORMARE PROFESIONALA IMPACT SRL'),
    ('F NOVATECH SRL'),
    ('F SC VECTRA EXIM SRL'),
    ('F SC GLOBAL SISTEM SRL'),
    ('F SC SERVICE ELECTROCASNICA SRL'),
    ('F SOCIETATEA ASIG ROM ASIROM VIENNA INSURANCE SA'),
    ('F PROIECT LG&CF. SRL'),
    ('SC EURO CONSTRUCT  SA'),
    ('F SC SPIACT CLUJ SA'),
    ('F SC VECTRA EUROLIFT SERVICE SRL'),
    ('F TIRIAC AUTO SRL'),
    ('F SC ASTRU GRUP SRL'),
    ('F SC CONTROL SERVICE SRL'),
    ('F PFA DUMITRU MARIANA'),
    ('F PFA HARALAMBIE GHEORGHE'),
    ('F  SC MANOPRINTING SYSTEM SRL'),
    ('F  SC SAMTEC  SRL'),
    ('F SC MEDIMPACT SA'),
    ('F CNCF CFR SA'),
    ('F BRESCIA PROD COM SRL'),
    ('F SC EURO CONSTRUCT SA'),
    ('F SC AVI EUROJOBS &TRAINING SRL'),
    ('F SC ABC  MEDICAL CENTER SRL'),
    ('F SC ARTEGO SA'),
    ('F SC RINO GUARD SRL'),
    ('F SC C&C PREVENT SRL'),
    ('F BCR SA'),
    ('F SC SELECT PRINT SRL'),
    ('F SC CALYPSA MONO SRL'),
    ('F SC ANDRAG REIGOS SRL'),
    ('F SC ONESTAR SECURITY SRL'),
    ('F SC RAMACLAU SRL'),
    ('F  SC EURO CONSTRUCT SA'),
    ('F SC ATMOSFERICA SRL'),
    ('F SC NOVA LIBRIS IMPEX SRL'),
    ('F SC TRADITIONALECO SRL'),
    ('F SC DIRALITEX COM SRL'),
    ('F PFA MECU ION'),
    ('F FAST BROKERS-BROKER DE ASIGURARE'),
    ('F SC NS COPIERS SRL'),
    ('F EKARA CLEANING SRL'),
    ('F SC TRANSGUARD SECURITY SRL'),
    ('F NIADA AUDITAX EXPERT SRL'),
    ('SC TRIVAS GRUP SRL'),
    ('SC START ASIG SRL'),
    ('SC TAPEL S.R.L'),
    ('F PFA PELINEL RICHARD-CATALIN'),
    ('F SC SAMTEC SRL'),
    ('F SC SALMIR IMPEX SRL'),
    ('F GROUPE EUROVEST INTERNATIONAL SRL'),
    ('F SC HEBOROM INTERNATIONAL SRL'),
    ('F SC DINALUCRI SRL'),
    ('F SC EUROCONSTRUCT SA'),
    ('F SC IRECSON EVALUĂRI SA'),
    ('CNCF CFR SA'),
    ('F SC NAGUMA MEDICAL SUPPLY SRL'),
    ('F SC NGM COMPANY SRL'),
    ('F SC C&C MEDIS VISION SRL'),
    ('F CS DRAGOSTAL SECURITY SRL'),
    ('F SC C$C PREVENT SRL'),
    ('F SC DAC TECHNOLOGY SRL'),
    ('F ABC MEDICAL CENTER SRL'),
    ('F SC NOVAINTERMED SRL'),
    ('F SC CALYPSO MONO  SRL'),
    ('F SC GROSSO SRL'),
    ('F SC UTI FACILITY MANAGEMENT SRL'),
    ('F NS COPIERS SRL'),
    ('F SC FRAHER DISTRIBUTION SRL'),
    ('F SC TINMAR ENERGY SA'),
    ('F SC PROIECT L.G .& C.F.SRL'),
    ('C SC ANDROMEDA SERV  SRL'),
    ('F SC MIRROR GROUP PRINT SRL'),
    ('F VOESTALPINE RAILWAY SYSTEMS ROMANIA S.A.'),
    ('F SC IRECSON EVALUARI SRL'),
    ('F ALLIANZ-TIRIAC ASIGURARI SA'),
    ('SC TRANSGUARD SECURITY SRL'),
    ('SC STONE CONSTRUCT SA'),
    ('PROIECT LG &CF'),
    ('SC ERGNUR INSTAL'),
    ('KOKKAI COMIMPEX'),
    ('ABC MEDICAL CENTER SRL'),
    ('ONE STAR SECURITY'),
    ('SC RINO GUARD SRL - SC DRAGOSTAL SECURITY SRL'),
    ('PROTECTCOLECTOR'),
    ('PRODITEX'),
    ('PYF PRODUCTION'),
    ('SC CONTROL SERVICE SRL'),
    ('BCR-CITY ONE'),
    ('RIK'),
    ('DNS BIROTICA'),
    ('PRIMOND'),
    ('RAMA CLAU'),
    ('CALYPSO MONO'),
    ('ECO ELECTRONICS SHOP'),
    ('ONE STAR SECURITY SRL'),
    ('UTI CONSTRUCTION AND FACILITY MANAGEMENT'),
    ('VOESTALPINE RAIL SYSTEM'),
    ('EURO CONSTRUCT'),
    ('TRADITIONAL ECO'),
    ('KOMART BLUE'),
    ('ASOCIATIA DE DEZVOLTARE PT ASISTENTA SOCIALA SI FORMARE PROFESIONALA'),
    ('TRANSGUARD SECURITY'),
    ('C &A COMPANY'),
    ('SERVICE ELECTROCASNICA'),
    ('PFA BARBA TASCU'),
    ('MIRROR GROUP'),
    ('ROTOTRANS'),
    ('EUROSTING AAW'),
    ('ASTRU GROUP'),
    ('CNCF CFR- SRCF CTA'),
    ('ANDROMEDA SERV'),
    ('NGM COMPANY'),
    ('DOLEX COM'),
    ('EUROPROTECT SAFETY'),
    ('GLOBAL SISTEM'),
    ('TRANSFER EXPERT LOGISTIC'),
    ('DRAGOSTAL TITAN GUARD'),
    ('EVALUARE SI EXPERTIZA OLARU SI ASOCIATII'),
    ('GAMA INK'),
    ('ASTI INTERNATIONAL'),
    ('TRIVAS GRUP'),
    ('ARCOTEX TRADE'),
    ('GARANT SECURITY'),
    ('PFA CUTURELA NICOLAE'),
    ('REMAT ECO METAL');
Select * from Furnizori
